name: spatialsfs
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - snakemake>=5.22
  - numpy>=1.19
  - matplotlib>=3.3
  - scipy
  - jupytext>=1.5.0
  - jupyterlab>=2.1
  - nodejs>=10.13
  - pytest
  - pytest-cov
  - pre-commit
